### ISSUE TITLE
globalThis.BigInt !== undefined when compiling

### ISSUE THREAD

**Issue by fenos** [timostamm/protobuf-ts#120]
Hello,

Using `"@protobuf-ts/plugin": "^2.0.0-alpha.27"` when i run the following command:

```
PROTOC_GEN_TS_BIN="./node_modules/.bin/protoc-gen-ts"
OUT_DIR="./generated"

protoc \
  -I ./protos \
  --plugin=protoc-gen-ts=$(PROTOC_GEN_TS_BIN) \
  --ts_opt=client_none \
  --ts_opt=generate_dependencies \
  --ts_out=$(OUT_DIR) \
  ./protos/*.proto
```

I get:

```
ReferenceError: globalThis is not defined
    at detectBi (/Users/fabrizio/Documents/Code/twirp-example/node_modules/@protobuf-ts/runtime/build/commonjs/pb-long.js:7:16)
    at Object.<anonymous> (/Users/fabrizio/Documents/Code/twirp-example/node_modules/@protobuf-ts/runtime/build/commonjs/pb-long.js:21:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/fabrizio/Documents/Code/twirp-example/node_modules/@protobuf-ts/runtime/build/commonjs/binary-reader.js:5:19)
--ts_out: protoc-gen-ts: Plugin failed with status code 1.
```

I'm not entirely sure why, any idea?

**Comment by fenos** [comment]
Damn!

I used `nvm` to switch to an older version of node, for another project and I forgot to switch back.

Facepalming my self.

All good
